import argparse
import warnings
import time
import random
from datetime import timedelta 
from stable_baselines3 import PPO
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.vec_env import SubprocVecEnv,VecNormalize
from stable_baselines3.common.logger import Logger, make_output_format

# -- Custom IMPORTS --
from src.workspace_manager import ExperimentWorkspace
from src.utils import *
from src.callbacks import *
from src.evaluation import evaluate_agent
from src.config import Config 


warnings.filterwarnings("ignore", message=".*pkg_resources is deprecated.*")

def run_training_cycle(iteration:int, seed_id:int):
    # For reproducibility and experiment validity
    random.seed(seed_id)
    np.random.seed(seed_id)
    torch.manual_seed(seed_id)

    start_time = time.perf_counter()
    # 1. Initialize Workspace, creates file structure for collected data
    ws = ExperimentWorkspace(iteration= iteration)
    print(f"🚀 [Iter {iteration}] Initializing Training in: {ws.model_root_path}")

    # Dynamic Code Loading
    # Logic: To train Iteration N, we need the code generated by Iteration N-1.
    reward_code_path = ws.get_path("code", iteration - 1, "reward.py")
    print(f"📥 Loading Reward Function from: {reward_code_path}")

    # Setup Hardware, helper functions for hardware-aware hyperparameter optimization
    n_envs, device = get_hardware_config()
    ppo_params = get_optimized_ppo_params(n_envs, device)

    # Create Environment, custom wrapper for injecting new Reward Function
    env = make_vec_env(lambda: make_env(reward_code_path), n_envs=n_envs, seed=seed_id,vec_env_cls=SubprocVecEnv)
    
    # Since LLMs are terrible with reward scaling, we are utilizing a running normalization of the reward
    env = VecNormalize(
        env,
        norm_obs=False,      # Must remain False so evaluation doesn't require loaded statistics
        norm_reward=True,    # Dynamically scales the LLM's arbitrary reward outputs to ~N(0,1)
        clip_reward=10.0,    # Hard clips extreme LLM hallucinations (e.g., if it outputs 50,000)
        gamma=0.99           # Must match your PPO gamma parameter
    )
    # Grab Path for saving raw data 
    logger_dir = ws.dirs["telemetry_iteration"] 
    progress_csv_suffix = f"_iter{iteration:02d}_seed{seed_id}"

    # Initialize Callbacks
    entropy_callback = EntropyScheduleCallback(
        initial_ent_coef=0.02,
        final_ent_coef=0.001,
        total_timesteps = Config.TOTAL_TIMESTEPS
        )

    behavior_tracker = MultiEnvEpisodeTracker(ws, iteration, seed_id, max_buffer_size=10000)

    output_formats = [
        # Optional: stdout logging
       # make_output_format("stdout", str(logger_dir), suffix),

        # Per-iteration CSV: telemetry_raw/progress_XXX.csv
        make_output_format("csv", str(logger_dir), progress_csv_suffix)
    ]
    logger = Logger(folder=str(logger_dir), output_formats=output_formats)

    lr_schedule = linear_schedule(1e-3, 3e-4)
    # 6. Train
    print(f"🏋️ Training on {device}")
    model = PPO(
        "MlpPolicy",
        env,
        device=ppo_params['device'],
        n_steps=ppo_params['n_steps'],                   
        batch_size=ppo_params['batch_size'],
        learning_rate=lr_schedule,
        n_epochs=10,
        gamma=0.99,
        gae_lambda=0.98,
        seed= seed_id,
        verbose=0
        )
    print(f"Model training with n_steps: {ppo_params['n_steps']}, batch_size: {ppo_params['batch_size']}")
    model.set_logger(logger)
    # Training Agent
    model.learn(
        total_timesteps=Config.TOTAL_TIMESTEPS, 
        callback=[entropy_callback, behavior_tracker]
    )
    # Close Env
    env.close()
    # 7. Save & Evaluate
    model_save_path = ws.get_path("models", iteration, f"model{seed_id}")
    model.save(model_save_path)
    
    print("📊 Running Evaluation")

    # Collect Evaluation Statistics and Merge 
    eval_data = evaluate_agent(
        model, 
        seed_id=seed_id,
        deterministic= True,
        reward_code_path=reward_code_path, 
        num_episodes=10
        )

    # Save Evaluation Data 
    eval_csv_path = ws.dirs['telemetry_iteration'] / f"iter{iteration:02d}_seed{seed_id}_eval.csv"
    pd.DataFrame(eval_data).to_csv(eval_csv_path,  mode='a', header=not eval_csv_path.exists(), index=False)

    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    # Format the output using timedelta
    print(f"✅ Training Cycle Complete | Seed {seed_id}")
    print(f"Execution took: {timedelta(seconds=elapsed_time)}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--iteration", type=int, required=True)
    parser.add_argument("--seed_id", type=int, required=True)
    args = parser.parse_args()
    
    run_training_cycle(args.iteration, args.seed_id)