"""
ARD post-hoc evaluation: extraction library.

Architecture:
    Per iteration we read FOUR structured sources and stitch them together:

      1. iter{NN}_metric_payload.json
         Deterministic RL outcome metrics. Generated by analysis.py from
         training/eval CSVs. Authoritative for: PSR, terminal distribution,
         ρ, SNR, CSI, per-component flags.

      2. iter{NN}_cognition_record.json
         The LLM call records. Authoritative for: proposal types, excisions,
         Research Lead selection. NOT used for outcome metrics — those
         metrics appear in the prompt text but represent the PRIOR
         iteration's diagnostic (the baseline-for-comparison section).

      3. experiment_ledger.json (single file at run root)
         The structured Validator verdicts. Authoritative for: status,
         post-mortem text.

       4. ChatResponse_data.csv  (joined to runs by row, not per-iter file)
        LLM compute data (durations, tokens) comes from a separate source

"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
import ast as _ast  # noqa: F401 


# ===========================================================================
# Path resolution
# ===========================================================================

class RunPaths:
    """
    Resolves every per-iteration file path under one campaign folder.
    Mirrors workspace_manager.py's layout exactly.
    """

    def __init__(self, campaign_path: Path):
        self.campaign_path = Path(campaign_path)
        model_dirs = [p for p in self.campaign_path.iterdir() if p.is_dir()]
        if len(model_dirs) != 1:
            raise ValueError(
                f"Expected exactly one model directory under {campaign_path}, "
                f"found {len(model_dirs)}: {[d.name for d in model_dirs]}")
        self.model_dir = model_dirs[0]
        self.cognition_json_dir = (self.model_dir
                                   / "cognition" / "json_cognition_records")
        self.metric_payload_dir = (self.model_dir
                                   / "telemetry" / "metric_payloads")
        self.ledger_path = self.model_dir / "cognition" / "experiment_ledger.json"
        self.chat_response_path = (self.model_dir
                                   / "cognition" / "ChatResponse_data.csv")
        self.code_dir = self.model_dir / "generated_code" 

    @property
    def campaign_tag(self) -> str:
        return self.campaign_path.name

    @property
    def model_dir_name(self) -> str:
        return self.model_dir.name

    def cognition_record(self, iteration: int) -> Path:
        return self.cognition_json_dir / f"iter{iteration:02d}_cognition_record.json"

    def metric_payload(self, iteration: int) -> Path:
        return self.metric_payload_dir / f"iter{iteration:02d}_metric_payload.json"

    def discover_iterations(self) -> list[int]:
        """Iteration numbers for which BOTH a payload and cognition record exist."""
        cog = set()
        for p in self.cognition_json_dir.glob("iter*_cognition_record.json"):
            m = re.match(r"iter(\d+)_", p.name)
            if m:
                cog.add(int(m.group(1)))
        pay = set()
        if self.metric_payload_dir.is_dir():
            for p in self.metric_payload_dir.glob("iter*_metric_payload.json"):
                m = re.match(r"iter(\d+)_", p.name)
                if m:
                    pay.add(int(m.group(1)))
        return sorted(cog & pay)
    
    def patch_file(self, iteration: int):          # → Path
        """Unified diff saved by standard.py each iteration."""
        return self.code_dir / f"iter{iteration:02d}_changes.patch"

    def reward_file(self, iteration: int):         # → Path
        """Accepted reward.py saved by standard.py each iteration."""
        return self.code_dir / f"iter{iteration:02d}_reward.py"



# ===========================================================================
# Metric payload loader (replaces regex-based outcome extraction)
# ===========================================================================

@dataclass
class OutcomeMetrics:
    """
    Deterministic outcome metrics for one iteration, loaded from the
    metric payload JSON. No regex, no markdown parsing.

    Landing rates (population_success_rate, all terminal_*_rate fields) are
    fractions 0-1, matching the payload's units.
    """
    # --- Optimization Dynamics ---
    cross_seed_cv: float | None
    cross_seed_reward_std: float | None
    mean_final_reward: float | None
    critic_saturation_index: float | None
    trajectory_isomorphism_rho: float | None
    is_initialization_sensitive: bool | None
    is_universally_converged: bool | None
    within_seed_terminal_cv: float | None
    is_terminal_unstable: bool | None
    critic_diverged: bool | None
    optimization_unstable: bool | None

    # --- Reward Topology ---
    objective_alignment_rho: float | None
    survival_hacking_rho: float | None
    survival_hacking_detected: bool | None
    topology_inverted: bool | None
    intra_rollout_cv: float | None
    terminal_entropy_norm: float | None
    systemic_policy_collapse: bool | None

    # --- Kinematic / Evaluation ---
    population_success_rate: float | None
    cross_seed_success_std: float | None
    is_lottery_ticket: bool | None
    mean_descent_efficiency: float | None
    efficiency_cv: float | None
    actuator_chatter_rate: float | None
    chatter_cv: float | None
    kinematically_sensitive: bool | None
    macro_oscillations: float | None
    lateral_instability: bool | None

    # --- Population Terminal Distribution (from evaluation rollouts) ---
    terminal_distribution: dict
    landed_centered_rate: float | None
    landed_off_centered_rate: float | None
    landed_off_centered_timeout_rate: float | None
    landed_slid_rate: float | None
    crashed_rate: float | None
    out_of_bounds_rate: float | None
    hover_timeout_rate: float | None

    # --- Component-level credit assignment ---
    components: dict
    n_components: int
    n_traitor: int
    n_dead_weight: int
    n_hidden_dependency: int
    n_optimal: int
    n_neutral_noisy: int
    n_hidden_traitor: int
    n_hidden_helper: int
    n_high_magnitude_neutral: int


def _safe_get(d, *keys, default=None):
    """Walk a nested dict; return default if any key is missing."""
    cur = d
    for k in keys:
        if not isinstance(cur, dict) or k not in cur:
            return default
        cur = cur[k]
    return cur


def _classify_component(comp: dict) -> str:
    # Priority order matters — earlier checks win.
    if comp.get("is_traitor_component"):           # covers both linear (rho < -0.2) and hidden traitors
        return "traitor"
    if comp.get("is_hidden_helper"):               # non-linear positive contributor
        return "hidden_helper"
    if comp.get("is_hidden_dependency"):           # non-linear, direction unresolved
        return "hidden_dependency"
    if comp.get("is_dead_weight"):
        return "dead_weight"
    if comp.get("is_high_magnitude_neutral"):      # high gradient share, indeterminate relationship
        return "high_magnitude_neutral"
    if abs(comp.get("alignment_rho") or 0.0) < 0.2:
        return "neutral_noisy"
    return "optimal"


def load_metric_payload(payload_path: Path) -> OutcomeMetrics:
    """Parse iter{NN}_metric_payload.json into a flat OutcomeMetrics struct."""
    with payload_path.open() as f:
        p = json.load(f)

    opt = _safe_get(p, "multi_seed_optimization_health") or {}
    stoch = _safe_get(p, "multi_seed_stochastic_health") or {}
    evalh = _safe_get(p, "multi_seed_evaluation_health") or {}

    # Evaluation distribution is what the diagnostic report renders.
    term = _safe_get(evalh, "failure_mode_analysis",
                     "population_terminal_distribution", default={}) or {}

    components = _safe_get(stoch, "dynamic_component_analysis",
                           default={}) or {}
    # Strip "reward_" prefix — it's payload noise.
    components_clean = {
        k.removeprefix("reward_"): v for k, v in components.items()
    }
    counts = {"traitor": 0, "hidden_dependency": 0, "dead_weight": 0,
              "neutral_noisy": 0, "optimal": 0,
              "hidden_helper": 0, "high_magnitude_neutral": 0}
    for v in components_clean.values():
        counts[_classify_component(v)] += 1
    n_hidden_traitor = sum(
        1 for v in components_clean.values() if v.get("is_hidden_traitor")
    )

    return OutcomeMetrics(
        cross_seed_cv=_safe_get(opt, "population_metrics", "cross_seed_cv"),
        cross_seed_reward_std=_safe_get(opt, "population_metrics",
                                        "cross_seed_reward_std"),
        mean_final_reward=_safe_get(opt, "population_metrics",
                                    "mean_final_reward"),
        critic_saturation_index=_safe_get(opt, "critic_robustness",
                                          "mean_critic_saturation_index"),
        trajectory_isomorphism_rho=_safe_get(opt, "learning_dynamics",
                                             "mean_trajectory_isomorphism_rho"),
        is_initialization_sensitive=_safe_get(opt, "summary_flags",
                                              "is_initialization_sensitive"),
        is_universally_converged=_safe_get(opt, "summary_flags",
                                           "is_universally_converged"),
        within_seed_terminal_cv=_safe_get(opt, "population_metrics",
                                          "within_seed_terminal_cv"),
        is_terminal_unstable=_safe_get(opt, "summary_flags",
                                       "is_terminal_unstable"),
        critic_diverged=_safe_get(opt, "critic_robustness",
                                  "systemic_critic_divergence_flag"),
        optimization_unstable=_safe_get(opt, "learning_dynamics",
                                        "highly_unstable_optimization_landscape_flag"),
        objective_alignment_rho=_safe_get(stoch, "global_reward_topology",
                                          "mean_objective_alignment_rho"),
        survival_hacking_rho=_safe_get(stoch, "global_reward_topology",
                                       "mean_survival_hacking_rho"),
        survival_hacking_detected=_safe_get(stoch, "global_reward_topology",
                                            "survival_hacking_detected_flag"),
        topology_inverted=_safe_get(stoch, "global_reward_topology",
                                    "topology_is_inverted_flag"),
        intra_rollout_cv=_safe_get(stoch, "policy_fragility",
                                   "mean_intra_rollout_cv"),
        terminal_entropy_norm=_safe_get(stoch, "policy_fragility",
                                        "mean_terminal_entropy_norm"),
        systemic_policy_collapse=_safe_get(stoch, "policy_fragility",
                                           "systemic_policy_collapse_flag"),
        population_success_rate=_safe_get(evalh, "success_robustness",
                                          "population_mean_success_rate"),
        cross_seed_success_std=_safe_get(evalh, "success_robustness",
                                         "cross_seed_success_std"),
        is_lottery_ticket=_safe_get(evalh, "success_robustness",
                                    "is_lottery_ticket_policy_flag"),
        mean_descent_efficiency=_safe_get(evalh, "kinematic_stability",
                                          "population_mean_efficiency"),
        efficiency_cv=_safe_get(evalh, "kinematic_stability",
                                "efficiency_coefficient_of_variation"),
        actuator_chatter_rate=_safe_get(evalh, "kinematic_stability",
                                        "population_mean_chatter_rate"),
        chatter_cv=_safe_get(evalh, "kinematic_stability",
                             "chatter_coefficient_of_variation"),
        kinematically_sensitive=_safe_get(evalh, "kinematic_stability",
                                          "kinematically_sensitive_to_initialization_flag"),
        macro_oscillations=_safe_get(evalh, "lateral_control",
                                     "population_mean_macro_oscillations"),
        lateral_instability=_safe_get(evalh, "lateral_control",
                                      "systemic_lateral_instability_flag"),
        terminal_distribution=term,
        landed_centered_rate=term.get("landed_centered"),
        landed_off_centered_rate=term.get("landed_off_centered"),
        landed_off_centered_timeout_rate=term.get("landed_off_centered_timeout"),
        landed_slid_rate=term.get("landed_but_slid_into_valley"),
        crashed_rate=term.get("crashed"),
        out_of_bounds_rate=term.get("out_of_bounds"),
        hover_timeout_rate=term.get("hover_timeout"),
        components=components_clean,
        n_components=len(components_clean),
        n_traitor=counts["traitor"],
        n_dead_weight=counts["dead_weight"],
        n_hidden_dependency=counts["hidden_dependency"],
        n_optimal=counts["optimal"],
        n_neutral_noisy=counts["neutral_noisy"],
        n_hidden_traitor=n_hidden_traitor,
        n_hidden_helper=counts["hidden_helper"],
        n_high_magnitude_neutral=counts["high_magnitude_neutral"],
    )


# ===========================================================================
# Ledger loader (Validator verdicts)
# ===========================================================================

# Status vocabulary observed in the ledger. Pyrrhic Victory / Productive
# Deviation / Goodhart Trap are richer-than-original-spec verdicts the
# Validator has adopted in practice, so we preserve them rather than
# collapsing to the original five-category vocabulary.
LEDGER_STATUS_VOCAB = (
    "Validated", "Confirmed",
    "Mixed", "Pyrrhic Victory", "Productive Deviation",
    "Inconclusive",
    "Refuted", "Regressed", "Goodhart Trap",
    "Unparsed",
)


@dataclass
class LedgerEntry:
    iteration: int
    hypothesis_text: str
    post_mortem_text: str | None
    status: str | None


def _extract_ledger_status(post_mortem: str | None) -> str | None:
    """Extract the verdict from `Status:` in the post-mortem; longest-match vs vocab."""
    if not post_mortem:
        return None
    m = re.search(r"\*\*Status:?\*\*\s*[`'\"]?\s*([A-Za-z][A-Za-z\- ]*)",
                  post_mortem)
    if not m:
        return None
    raw = m.group(1).strip().strip("`'\"").rstrip(" -").strip()
    raw_lower = raw.lower()
    best = None
    for v in LEDGER_STATUS_VOCAB:
        if v == "Unparsed":
            continue
        if raw_lower.startswith(v.lower()):
            if best is None or len(v) > len(best):
                best = v
    if best:
        return best
    return raw.split()[0] if raw else None


def load_ledger(ledger_path: Path) -> dict[int, LedgerEntry]:
    """Load the experiment ledger; return {iteration: LedgerEntry}."""
    if not ledger_path.is_file():
        return {}
    with ledger_path.open() as f:
        d = json.load(f)
    out = {}
    for exp in d.get("experiments", []):
        it = exp["id"]
        out[it] = LedgerEntry(
            iteration=it,
            hypothesis_text=exp.get("hypothesis_payload", "") or "",
            post_mortem_text=exp.get("validation_post_mortem"),
            status=_extract_ledger_status(exp.get("validation_post_mortem")),
        )
    return out


# ===========================================================================
# Cognition record parser — LLM-behaviour fields only
# ===========================================================================

PROP_TYPES = ("modification", "addition", "cluster", "unknown")


@dataclass
class ProposalRecord:
    index: int
    header: str
    inferred_type: str
    type_evidence: str


def _infer_proposal_type(body: str, header: str) -> tuple[str, str]:
    """Classify a Strategist proposal as Modification / Addition / Cluster."""
    h = header.lower()
    body_l = body.lower()

    paren = re.search(r"\(([^)]+)\)\s*$", header)
    if paren:
        ptxt = paren.group(1).lower()
        if "cluster" in ptxt or "synergistic" in ptxt:
            return "cluster", f"header:{paren.group(1)}"
        if "modification" in ptxt or "modify" in ptxt:
            return "modification", f"header:{paren.group(1)}"
        if "addition" in ptxt or "add" in ptxt:
            return "addition", f"header:{paren.group(1)}"

    # Cluster signals first — "replace X and Y with a single unified term"
    # describes a cluster, not a one-component rescale. Cheap two-step check
    # avoids catastrophic backtracking from nested-quantifier regex.
    if re.search(r"\bsynergistic\s+cluster\b|\bcluster\b.*\bsynerg", body_l):
        return "cluster", "body:synergistic-cluster"
    UNIFY_TARGETS = ("a single", "single unified", "synergistic term",
                     "unified term", "combined term", "into a single",
                     "merged into")
    if (re.search(r"\b(?:replac|modif|merg|combin|unif)[a-z]*\b", body_l)
            and any(t in body_l for t in UNIFY_TARGETS)):
        return "cluster", "body:multi-into-single"
    if re.search(r"\bcluster\b", h):
        return "cluster", "header:cluster"

    if re.search(r"\breplac(?:e|ing)\b\s+(?:the\s+)?[`\w_]+", body_l):
        return "modification", "body:replace"
    if "**replace**" in body_l:
        return "modification", "body:replace-bold"
    if re.search(r"\*\*modify\*\*|\bmodify\s+(?:the\s+)?[`\w]+", body_l):
        return "modification", "body:modify"
    if "old form" in body_l and "new form" in body_l:
        return "modification", "body:old-new-form"
    if re.search(r"\b(?:invert|inversion|sign\s+inversion|rescale|gating?|gate\s+by)\b",
                 body_l):
        return "modification", "body:invert-rescale-gate"
    if re.search(r"\*\*add\*\*|\badd\s+a\s+new\s+component\b|\bnew\s+term\s*[:\.]",
                 body_l):
        return "addition", "body:add-new"
    # "Add the following term", "Add a term", "Add this term"
    if re.search(r"\badd\s+(?:the\s+following|a|this|new)\s+(?:term|component|reward|bonus|penalty)\b",
                 body_l):
        return "addition", "body:add-following"
    if re.search(r"\bpropose\s+(?:adding|introducing)\b|\bintroduc(?:e|ing)\s+a\s+new\b",
                 body_l):
        return "addition", "body:propose-add"

    return "unknown", ""


def _parse_strategist_excisions(response: str) -> int | None:
    """Count components excised in PART 1 of the Strategist response."""
    part1 = re.search(r"PART 1[^\n]*\n(.*?)(?:PART 2|\Z|\*\*PART 2)",
                      response, re.DOTALL | re.IGNORECASE)
    if not part1:
        return None
    text = part1.group(1)
    if re.search(r"no components?\s+(?:are\s+)?(?:being\s+)?excised", text, re.I):
        return 0
    return len(re.findall(r"^\s*[\*\-]\s+\*\*", text, re.MULTILINE))


def _parse_strategist_proposals(response: str) -> list[ProposalRecord]:
    matches = list(re.finditer(r"^###\s*Proposal\s*(\d+)[^\n]*",
                               response, re.MULTILINE))
    if not matches:
        return []
    proposals = []
    for i, m in enumerate(matches):
        header = m.group(0).lstrip("# ").strip()
        idx = int(m.group(1))
        body_start = m.end()
        body_end = (matches[i + 1].start()
                    if i + 1 < len(matches) else len(response))
        body = response[body_start:body_end]
        ptype, evidence = _infer_proposal_type(body, header)
        proposals.append(ProposalRecord(
            index=idx, header=header,
            inferred_type=ptype, type_evidence=evidence))
    return proposals


def _parse_rl_selection(response: str) -> tuple[int | None, str | None]:
    m = re.search(r"\*\*Selected Proposal:?\*\*\s*Proposal\s*(\d+)\s*:?\s*([^\n]*)",
                  response)
    if not m:
        m = re.search(r"EXECUTIVE DECISION.*?Proposal\s*(\d+)\s*:?\s*([^\n]*)",
                      response, re.DOTALL | re.IGNORECASE)
        if not m:
            return None, None
    return int(m.group(1)), m.group(2).strip()


@dataclass
class CognitionRecord:
    """LLM behaviour for one iteration (no outcome metrics here)."""
    iteration: int
    strategist_model: str
    role_models: dict
    excision_count: int | None
    proposal_type_counts: dict
    proposals: list
    selected_proposal_index: int | None
    selected_proposal_header: str | None
    parse_warnings: list = field(default_factory=list)

@dataclass
class CodeChangeRecord:
    """
    Ground-truth code-level changes for one iteration.

    Sources
    -------
    Diff stats (lines_added / lines_removed / n_hunks):
        Parsed from iter{N}_changes.patch.  Raw signal only — no attempt to
        track the components block through diff prefixes.

    Component delta (excised_components / added_components):
        AST set-difference between iter{N-1}_reward.py and iter{N}_reward.py.
        This is immune to the Strategist's self-reported PART 1 prose, which
        can silently undercount (e.g. iter06: "no excisions" while
        landing_stability_synergy was actually removed from the dict).

    Structural integrity (double_count_flags / ghost_vars):
        AST analysis of iter{N}_reward.py only.
        double_count_flags: component pairs whose expanded r_* variable sets
            overlap, meaning the same intermediate quantity appears in total_reward
            more than once.
        ghost_vars: r_* variables assigned in the function body but not reachable
            (directly or transitively through other r_* assignments) from any
            component dict value.  Benign aggregation aliases (r_landing etc.)
            appear here; treat as low-severity unless the name matches a key that
            was expected to be tracked.
    """
    iteration: int
    # Raw diff statistics
    lines_added: int
    lines_removed: int
    n_hunks: int
    patch_available: bool
    # Component-level delta (AST comparison: curr vs prev reward.py)
    excised_components: list   # component keys present in prev but absent in curr
    added_components: list     # component keys absent in prev but present in curr
    n_excised: int
    n_added: int
    # Current-iteration structural integrity (AST of curr reward.py)
    component_names: list      # ordered keys in components dict this iteration
    n_components: int
    double_count_flags: list   # [{component_a, component_b, shared_r_vars}]
    ghost_vars: list           # r_* vars computed but not reachable from components
    ast_available: bool
    warnings: list


def extract_cognition_record(record_path: Path) -> CognitionRecord:
    """Parse iter{NN}_cognition_record.json — LLM behaviour fields only."""
    with record_path.open() as f:
        data = json.load(f)

    iteration = data["iteration"]
    strategist_model = data.get("model_name", "")
    calls_by_phase = {c["phase"]: c for c in data["calls"]}
    role_models = {phase: c.get("model_name", "")
                   for phase, c in calls_by_phase.items()}
    warnings: list[str] = []

    strat_call = calls_by_phase.get("strategist")
    if strat_call is None:
        warnings.append("missing_strategist_call")
        excision_count = None
        proposals = []
    else:
        resp = strat_call["response_content"] or ""
        excision_count = _parse_strategist_excisions(resp)
        proposals = _parse_strategist_proposals(resp)
        if not proposals:
            warnings.append("no_proposals_parsed")
        for p in proposals:
            if p.inferred_type == "unknown":
                warnings.append(f"proposal_{p.index}_type_unknown")

    proposal_type_counts = {t: 0 for t in PROP_TYPES}
    for p in proposals:
        proposal_type_counts[p.inferred_type] = \
            proposal_type_counts.get(p.inferred_type, 0) + 1

    rl_call = calls_by_phase.get("research_lead")
    if rl_call is None:
        warnings.append("missing_research_lead_call")
        selected_idx, selected_header = None, None
    else:
        selected_idx, selected_header = _parse_rl_selection(
            rl_call["response_content"] or "")
        if selected_idx is None:
            warnings.append("selection_unparsed")

    return CognitionRecord(
        iteration=iteration,
        strategist_model=strategist_model,
        role_models=role_models,
        excision_count=excision_count,
        proposal_type_counts=proposal_type_counts,
        proposals=proposals,
        selected_proposal_index=selected_idx,
        selected_proposal_header=selected_header,
        parse_warnings=warnings,
    )

def _collect_r_names(node) -> set:
    """Collect all Name.id values matching r_* from an AST subtree."""
    return {
        n.id for n in _ast.walk(node)
        if isinstance(n, _ast.Name) and n.id.startswith("r_")
    }


def analyze_reward_ast(source: str) -> dict:
    """
    Parse reward.py source and return structural analysis.

    Double-count detection
    ~~~~~~~~~~~~~~~~~~~~~~
    For each component, collect the r_* variables its value expression
    references directly, then expand one level through the function's
    r_* assignment graph.  Two components are flagged as a double-count
    pair when their expanded sets overlap — meaning the same intermediate
    quantity is summed into total_reward more than once.

    Example (iter05):
        action_smoothness         = float(r_smooth)   → expanded: {r_smooth}
        lateral_damping           = float(r_lateral)  → expanded: {r_lateral}
        landing_stability_synergy = float(r_lss)
            where r_lss = r_smooth + r_lateral        → expanded: {r_lss, r_smooth, r_lateral}
        → pairs flagged: (synergy ↔ action_smoothness), (synergy ↔ lateral_damping)

    Ghost variable detection
    ~~~~~~~~~~~~~~~~~~~~~~~~
    Any r_* variable assigned in the function body but not in the union of
    all expanded component variable sets is a ghost.  Aggregation aliases
    (r_landing = r_a + r_b + r_c, where a/b/c are individually tracked)
    always appear here; flag them but treat as informational.

    Returns a dict; parse_error is None on success.
    """
    _EMPTY = {
        "component_names": [], "n_components": 0,
        "double_count_flags": [], "ghost_vars": [],
        "parse_error": None,
    }
    try:
        tree = _ast.parse(source)
    except SyntaxError as exc:
        return {**_EMPTY, "parse_error": str(exc)}

    func = next(
        (n for n in _ast.walk(tree)
         if isinstance(n, _ast.FunctionDef) and n.name == "calculate_reward"),
        None,
    )
    if func is None:
        return {**_EMPTY, "parse_error": "calculate_reward not found"}

    # Build r_* variable dependency map: var → set of r_* vars its RHS references
    r_var_deps: dict = {}
    for node in _ast.walk(func):
        if isinstance(node, _ast.Assign):
            for target in node.targets:
                if isinstance(target, _ast.Name) and target.id.startswith("r_"):
                    r_var_deps[target.id] = _collect_r_names(node.value)

    # Locate the `components = { ... }` assignment
    comp_dict = None
    for node in _ast.walk(func):
        if (isinstance(node, _ast.Assign)
                and any(isinstance(t, _ast.Name) and t.id == "components"
                        for t in node.targets)
                and isinstance(node.value, _ast.Dict)):
            comp_dict = node.value
            break
    if comp_dict is None:
        return {**_EMPTY, "parse_error": "components dict not found"}

    # Extract component_name → directly referenced r_* vars
    component_names: list = []
    comp_r_refs: dict = {}
    for key_node, val_node in zip(comp_dict.keys, comp_dict.values):
        if not (isinstance(key_node, _ast.Constant)
                and isinstance(key_node.value, str)):
            continue
        comp_name = key_node.value
        component_names.append(comp_name)
        # Unwrap float(expr) if present so we inspect the actual expression
        inner = (val_node.args[0]
                 if isinstance(val_node, _ast.Call) and val_node.args
                 else val_node)
        comp_r_refs[comp_name] = _collect_r_names(inner)

    def _expand(r_vars: set) -> set:
        """One-level expansion through r_* assignment graph."""
        expanded = set(r_vars)
        for v in r_vars:
            expanded |= r_var_deps.get(v, set())
        return expanded

    # Double-count: flag all pairs (A, B) with overlapping expanded r_* sets
    double_count_flags: list = []
    comp_items = list(comp_r_refs.items())
    for i, (comp_a, refs_a) in enumerate(comp_items):
        exp_a = _expand(refs_a)
        for comp_b, refs_b in comp_items[i + 1:]:
            exp_b = _expand(refs_b)
            overlap = exp_a & exp_b
            if overlap:
                double_count_flags.append({
                    "component_a": comp_a,
                    "component_b": comp_b,
                    "shared_r_vars": sorted(overlap),
                })

    # Ghost detection: r_* vars not reachable from any component value
    all_comp_r_vars: set = set()
    for refs in comp_r_refs.values():
        all_comp_r_vars |= _expand(refs)
    ghost_vars = sorted(v for v in r_var_deps if v not in all_comp_r_vars)

    return {
        "component_names": component_names,
        "n_components": len(component_names),
        "double_count_flags": double_count_flags,
        "ghost_vars": ghost_vars,
        "parse_error": None,
    }


def parse_reward_diff(patch_text: str) -> dict:
    """
    Extract raw diff statistics from a unified diff of reward.py.

    Deliberately minimal: only lines_added, lines_removed, n_hunks.
    Component-level excision/addition is derived via AST comparison in
    load_code_change, not from diff text — tracking brace depth through
    diff prefixes is fragile when hunks split the components block.
    """
    lines_added = lines_removed = n_hunks = 0
    for line in patch_text.splitlines():
        if line.startswith("@@"):
            n_hunks += 1
        elif line.startswith("+") and not line.startswith("+++"):
            lines_added += 1
        elif line.startswith("-") and not line.startswith("---"):
            lines_removed += 1
    return {
        "lines_added": lines_added,
        "lines_removed": lines_removed,
        "n_hunks": n_hunks,
    }


def load_code_change(paths, iteration: int) -> CodeChangeRecord:
    """
    Load and derive all code-change metrics for one iteration.

    Patch file  → raw diff statistics.
    curr reward.py AST → component_names, double_count_flags, ghost_vars.
    prev reward.py AST → component_names for set-difference (excised/added).

    For iteration 1 there is no iter00_reward.py; all current components
    are treated as "added" and a non-critical warning is emitted.
    """
    warnings: list = []

    # ── Patch: raw diff statistics ──
    patch_path = paths.patch_file(iteration)
    patch_available = patch_path.is_file()
    lines_added = lines_removed = n_hunks = 0
    if patch_available:
        try:
            stats = parse_reward_diff(patch_path.read_text(encoding="utf-8"))
            lines_added   = stats["lines_added"]
            lines_removed = stats["lines_removed"]
            n_hunks       = stats["n_hunks"]
        except Exception as exc:
            warnings.append(f"patch_parse_error:{exc}")
            patch_available = False
    else:
        warnings.append("patch_missing")

    # ── Current reward.py: structural analysis ──
    curr_path = paths.reward_file(iteration)
    ast_available = curr_path.is_file()
    curr_analysis: dict = {}
    if ast_available:
        try:
            curr_analysis = analyze_reward_ast(curr_path.read_text(encoding="utf-8"))
            if curr_analysis.get("parse_error"):
                warnings.append(f"ast_error:{curr_analysis['parse_error']}")
                ast_available = False
        except Exception as exc:
            warnings.append(f"ast_error:{exc}")
            ast_available = False
    else:
        warnings.append("reward_py_missing")

    curr_components = curr_analysis.get("component_names", [])

    # ── Previous reward.py: component names for set-difference ──
    prev_path = paths.reward_file(iteration - 1)
    prev_components: list = []
    if prev_path.is_file():
        try:
            prev_analysis = analyze_reward_ast(prev_path.read_text(encoding="utf-8"))
            if not prev_analysis.get("parse_error"):
                prev_components = prev_analysis.get("component_names", [])
            else:
                warnings.append(f"prev_ast_error:{prev_analysis['parse_error']}")
        except Exception as exc:
            warnings.append(f"prev_ast_error:{exc}")
    elif iteration == 1:
        warnings.append("iter1_no_prev_baseline")
    else:
        warnings.append(f"prev_reward_py_missing:iter{iteration - 1:02d}")

    curr_set = set(curr_components)
    prev_set = set(prev_components)
    excised = sorted(prev_set - curr_set)
    added   = sorted(curr_set - prev_set)

    return CodeChangeRecord(
        iteration=iteration,
        lines_added=lines_added,
        lines_removed=lines_removed,
        n_hunks=n_hunks,
        patch_available=patch_available,
        excised_components=excised,
        added_components=added,
        n_excised=len(excised),
        n_added=len(added),
        component_names=curr_components,
        n_components=len(curr_components),
        double_count_flags=curr_analysis.get("double_count_flags", []),
        ghost_vars=curr_analysis.get("ghost_vars", []),
        ast_available=ast_available,
        warnings=warnings,
    )


# ===========================================================================
# Per-iteration assembly
# ===========================================================================

@dataclass
class IterationRecord:
    """Everything we know about one iteration of one run."""
    iteration: int
    campaign_tag: str
    model_dir: str
    strategist_model: str
    role_models: dict
    outcomes: OutcomeMetrics
    cognition: CognitionRecord
    code_change: "CodeChangeRecord | None"
    validator_status: str | None
    ledger_hypothesis: str
    ledger_post_mortem: str | None
    parse_warnings: list = field(default_factory=list)


def assemble_iteration(paths: RunPaths, iteration: int,
                       ledger: dict[int, LedgerEntry]) -> IterationRecord:
    """Combine payload + cognition record + ledger into one IterationRecord."""
    warnings: list[str] = []

    payload_path = paths.metric_payload(iteration)
    cognition_path = paths.cognition_record(iteration)
    if not payload_path.is_file():
        raise FileNotFoundError(f"Missing payload: {payload_path}")
    if not cognition_path.is_file():
        raise FileNotFoundError(f"Missing cognition record: {cognition_path}")

    outcomes = load_metric_payload(payload_path)
    cognition = extract_cognition_record(cognition_path)
    warnings.extend(cognition.parse_warnings)
    try:
        code_change = load_code_change(paths, iteration)
        # Suppress the expected iter-1 baseline warning from top-level parse_warnings
        # to keep it out of the Pipeline Performance dashboard's warning counts.
        for w in code_change.warnings:
            if not w.startswith("iter1_no_prev"):
                warnings.append(f"code:{w}")
    except Exception as exc:
        code_change = None
        warnings.append(f"code_change_load_error:{exc}")

    ledger_entry = ledger.get(iteration)
    if ledger_entry is None:
        warnings.append("missing_ledger_entry")
        validator_status = None
        hypothesis       = ""
        post_mortem      = None
    else:
        validator_status = ledger_entry.status
        hypothesis       = ledger_entry.hypothesis_text
        post_mortem      = ledger_entry.post_mortem_text
        # Final iteration of a run will typically have post_mortem=None
        # because the Validator writes it at the start of iter N+1, which
        # never happens. Flag it so the dashboard can render distinctly.
        if post_mortem is None:
            warnings.append("ledger_post_mortem_pending")

    return IterationRecord(
        iteration=iteration,
        campaign_tag=paths.campaign_tag,
        model_dir=paths.model_dir_name,
        strategist_model=cognition.strategist_model,
        role_models=cognition.role_models,
        outcomes=outcomes,
        cognition=cognition,
        code_change=code_change,
        validator_status=validator_status,
        ledger_hypothesis=hypothesis,
        ledger_post_mortem=post_mortem,
        parse_warnings=warnings,
    )


# ===========================================================================
# Per-run aggregation
# ===========================================================================

@dataclass
class AggregationConfig:
    """Thresholds for behavioural-event detection within a run."""
    # Landing rates are fractions 0-1, matching the payload's units.
    established_floor: float = 0.40
    regression_k: float = 2.0
    regression_min_floor_pp: float = 10.0
    recovery_window: int = 0
    primary_landing_metric: str = "psr"


@dataclass
class RunSummary:
    campaign_tag: str
    model_dir: str
    strategist_model: str
    iteration_count: int
    peak_psr: float | None
    peak_centered: float | None
    iter_final_psr: float | None
    iter_final_centered: float | None
    collapse_count: int
    recovery_count: int
    stability_score: float | None
    total_excisions: int
    mean_excisions_per_iter: float
    total_proposals_by_type: dict
    mean_proposals_by_type: dict
    validator_verdicts: dict
    iterations: list
    iterations_with_warnings: int


def _safe_max(values):
    vs = [v for v in values if v is not None]
    return max(vs) if vs else None


def _safe_std(values):
    vs = [v for v in values if v is not None]
    if len(vs) < 2:
        return None
    mean = sum(vs) / len(vs)
    return (sum((v - mean) ** 2 for v in vs) / len(vs)) ** 0.5


def _mean(values):
    vs = [v for v in values if v is not None]
    return (sum(vs) / len(vs)) if vs else None


def _count_collapses_recoveries(rates, collapse_threshold=0.10, recovery_threshold=0.50,
                                recovery_window=0):
    """Walk landing-rate sequence; count collapse/recovery events. (Unused — kept for reference.)"""
    collapses = 0
    recoveries = 0
    last_collapse_idx = None
    for i, r in enumerate(rates):
        if r is None:
            continue
        if r < collapse_threshold:
            collapses += 1
            last_collapse_idx = i
        elif r >= recovery_threshold and last_collapse_idx is not None:
            in_window = (recovery_window == 0
                         or (i - last_collapse_idx) <= recovery_window)
            if in_window:
                recoveries += 1
                last_collapse_idx = None
    return collapses, recoveries


def aggregate_run(iterations, cfg=None):
    cfg = cfg or AggregationConfig()
    if not iterations:
        raise ValueError("aggregate_run: empty iteration list")
    iterations = list(iterations)

    psrs = [it.outcomes.population_success_rate for it in iterations]
    cents = [it.outcomes.landed_centered_rate for it in iterations]

    total_excisions = sum(it.cognition.excision_count or 0 for it in iterations)
    mean_excisions = total_excisions / len(iterations)

    total_props = {t: 0 for t in PROP_TYPES}
    for it in iterations:
        for t, c in it.cognition.proposal_type_counts.items():
            total_props[t] = total_props.get(t, 0) + c
    mean_props = {t: total_props[t] / len(iterations) for t in total_props}

    verdicts = {}
    for it in iterations:
        v = it.validator_status or "Unparsed"
        verdicts[v] = verdicts.get(v, 0) + 1

    return RunSummary(
        campaign_tag=iterations[0].campaign_tag,
        model_dir=iterations[0].model_dir,
        strategist_model=iterations[0].strategist_model,
        iteration_count=len(iterations),
        peak_psr=_safe_max(psrs),
        peak_centered=_safe_max(cents),
        iter_final_psr=psrs[-1],
        iter_final_centered=cents[-1],
        collapse_count=0,
        recovery_count=0,
        stability_score=_safe_std(psrs),
        total_excisions=total_excisions,
        mean_excisions_per_iter=mean_excisions,
        total_proposals_by_type=total_props,
        mean_proposals_by_type=mean_props,
        validator_verdicts=verdicts,
        iterations=iterations,
        iterations_with_warnings=sum(1 for it in iterations if it.parse_warnings),
    )


def load_run(campaign_path, cfg=None):
    """Load every iteration in a campaign folder; return RunSummary."""
    paths = RunPaths(Path(campaign_path))
    ledger = load_ledger(paths.ledger_path)
    iters = paths.discover_iterations()
    if not iters:
        raise FileNotFoundError(f"No iterations found under {campaign_path}")
    records = [assemble_iteration(paths, it, ledger) for it in iters]
    return aggregate_run(records, cfg)


# ===========================================================================
# Cross-run aggregation
# ===========================================================================

@dataclass
class ModelSummary:
    """One row per (model configuration, campaign signature) for the paper."""
    strategist_model: str
    campaign_signature: str
    n_runs: int
    peak_psr_mean: float | None
    peak_psr_std: float | None
    peak_centered_mean: float | None
    peak_centered_std: float | None
    iter_final_psr_mean: float | None
    iter_final_psr_std: float | None
    iter_final_centered_mean: float | None
    iter_final_centered_std: float | None
    collapse_count_mean: float
    collapse_count_std: float | None
    recovery_count_mean: float
    recovery_count_std: float | None
    stability_score_mean: float | None
    stability_score_std: float | None
    mean_excisions_per_iter_across_runs: float
    proposal_type_mean_per_iter: dict
    run_summaries: list


def aggregate_across_runs(runs, campaign_signature: str = ""):
    if not runs:
        raise ValueError("aggregate_across_runs: empty run list")
    models = {r.strategist_model for r in runs}
    if len(models) > 1:
        raise ValueError(
            f"aggregate_across_runs: runs span multiple models: {models}")

    peak_psrs = [r.peak_psr for r in runs]
    peak_cents = [r.peak_centered for r in runs]
    final_psrs = [r.iter_final_psr for r in runs]
    final_cents = [r.iter_final_centered for r in runs]
    collapses = [r.collapse_count for r in runs]
    recoveries = [r.recovery_count for r in runs]
    stabilities = [r.stability_score for r in runs]

    prop_type_means = {}
    for t in PROP_TYPES:
        prop_type_means[t] = _mean([r.mean_proposals_by_type.get(t, 0)
                                    for r in runs])

    return ModelSummary(
        strategist_model=models.pop(),
        campaign_signature=campaign_signature,
        n_runs=len(runs),
        peak_psr_mean=_mean(peak_psrs),
        peak_psr_std=_safe_std(peak_psrs),
        peak_centered_mean=_mean(peak_cents),
        peak_centered_std=_safe_std(peak_cents),
        iter_final_psr_mean=_mean(final_psrs),
        iter_final_psr_std=_safe_std(final_psrs),
        iter_final_centered_mean=_mean(final_cents),
        iter_final_centered_std=_safe_std(final_cents),
        collapse_count_mean=_mean(collapses) or 0.0,
        collapse_count_std=_safe_std(collapses),
        recovery_count_mean=_mean(recoveries) or 0.0,
        recovery_count_std=_safe_std(recoveries),
        stability_score_mean=_mean(stabilities),
        stability_score_std=_safe_std(stabilities),
        mean_excisions_per_iter_across_runs=_mean(
            [r.mean_excisions_per_iter for r in runs]) or 0.0,
        proposal_type_mean_per_iter=prop_type_means,
        run_summaries=runs,
    )


# ===========================================================================
# LLM compute data (ChatResponse_data.csv)
# ===========================================================================

def load_chat_responses(csv_path, cognition_json_dir=None):
    """
    Load ChatResponse_data.csv into a list of typed dicts.

    If cognition_json_dir is provided, response_content and thinking_trace
    are joined in from iter{NN}_cognition_record.json for the output size
    breakdown in the compute cost dashboard.

    Nanosecond durations are converted to seconds (stored alongside the
    originals under _s suffix). Numeric columns are coerced. The CSV
    already has one row per LLM call, so this is just type-cleaning.
    """
    import csv as _csv
    csv_path = Path(csv_path)
    if not csv_path.is_file():
        return []
    rows = []
    NS_COLS = ("total_duration_ns", "load_duration_ns",
               "prompt_eval_duration_ns", "eval_duration_ns")
    INT_COLS = ("iteration", "num_tool_calls",
                "prompt_eval_count", "eval_count")
    FLOAT_COLS = ("opt_temperature", "opt_top_p", "opt_top_k",
                  "opt_repeat_penalty", "opt_num_ctx", "opt_num_predict")
    with csv_path.open() as f:
        for r in _csv.DictReader(f):
            for c in NS_COLS:
                ns = r.get(c, "")
                if ns:
                    try:
                        ns_v = int(ns)
                        r[c] = ns_v
                        r[c.replace("_ns", "_s")] = ns_v / 1e9
                    except ValueError:
                        r[c] = None
            for c in INT_COLS:
                v = r.get(c, "")
                if v:
                    try:
                        r[c] = int(v)
                    except ValueError:
                        r[c] = None
            for c in FLOAT_COLS:
                v = r.get(c, "")
                if v:
                    try:
                        r[c] = float(v)
                    except ValueError:
                        r[c] = None
            # Ensure these keys always exist; populated by join below if available
            r.setdefault("response_content", "")
            r.setdefault("thinking_trace", "")
            rows.append(r)

    # Join response_content + thinking_trace from cognition JSON records.
    # Builds a lookup: {(iteration, phase) -> (response_content, thinking_trace)}
    if cognition_json_dir is not None:
        cog_dir = Path(cognition_json_dir)
        _lookup: dict[tuple[int, str], tuple[str, str]] = {}
        for json_path in sorted(cog_dir.glob("iter*_cognition_record.json")):
            try:
                with json_path.open() as jf:
                    data = json.load(jf)
                it_num = data.get("iteration")
                for call in data.get("calls", []):
                    phase = call.get("phase", "")
                    content = call.get("response_content") or ""
                    thinking = call.get("thinking_trace") or ""
                    if it_num is not None and phase:
                        _lookup[(it_num, phase)] = (content, thinking)
            except Exception:
                continue
        for r in rows:
            it = r.get("iteration")
            phase = r.get("phase", "")
            if it is not None:
                content, thinking = _lookup.get((it, phase), ("", ""))
                r["response_content"] = content
                r["thinking_trace"] = thinking

    return rows


# ===========================================================================
# CLI smoke test
# ===========================================================================

if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print("Usage: python3 extract_cognition.py <campaign_path>")
        print("Or:    python3 extract_cognition.py --smoke-test")
        sys.exit(1)

    if sys.argv[1] == "--smoke-test":
        upload = Path("/mnt/user-data/uploads")
        print("=== Per-iteration extraction smoke test ===\n")
        for it in (1, 2, 3, 7, 8):
            payload_path = upload / f"iter{it:02d}_metric_payload.json"
            if not payload_path.is_file():
                continue
            outcomes = load_metric_payload(payload_path)
            print(f"iter {it:>2}: "
                  f"PSR={outcomes.population_success_rate} "
                  f"centered={outcomes.landed_centered_rate} "
                  f"ρ={outcomes.objective_alignment_rho} "
                  f"CV={outcomes.cross_seed_cv} "
                  f"comps={outcomes.n_components}")
            cog_path = upload / f"iter{it:02d}_cognition_record.json"
            if cog_path.is_file():
                cog = extract_cognition_record(cog_path)
                print(f"         excise={cog.excision_count} "
                      f"props={cog.proposal_type_counts} "
                      f"sel=P{cog.selected_proposal_index}")

        print("\n=== Ledger smoke test ===")
        ledger = load_ledger(upload / "experiment_ledger.json")
        for it, e in sorted(ledger.items()):
            pend = " (pending)" if e.post_mortem_text is None else ""
            print(f"  iter {it:>2}: status={e.status!r}{pend}")

        print("\n=== ChatResponse smoke test ===")
        chats = load_chat_responses(upload / "ChatResponse_data.csv")
        print(f"  rows: {len(chats)}")
        if chats:
            r = chats[0]
            print(f"  sample: iter={r['iteration']} phase={r['phase']} "
                  f"model={r['model_name']} "
                  f"prompt_tok={r['prompt_eval_count']} "
                  f"gen_tok={r['eval_count']} "
                  f"total_s={r['total_duration_s']:.1f}")
        sys.exit(0)

    summary = load_run(Path(sys.argv[1]))
    print(f"Run: {summary.campaign_tag}/{summary.model_dir}")
    print(f"  iterations={summary.iteration_count} "
          f"peak_psr={summary.peak_psr} "
          f"collapses={summary.collapse_count} "
          f"recoveries={summary.recovery_count}")
    print(f"  verdicts={summary.validator_verdicts}")
