import time
import re
from datetime import datetime, timedelta 
import warnings
warnings.filterwarnings("ignore", message=".*pkg_resources is deprecated.*")

# -- PROJECT IMPORTS --
import src.prompts as prompts  
from src.workspace_manager import ExperimentWorkspace
from src.code_validation import CodeValidator
from src.ledger import ExperimentLedger
from src.config import Config
from src.cognitive_node import CognitiveNode
from src.utils import extract_python_code

MODEL_NAME = "gpt-oss:20b"
#MODEL_NAME = Config.LLM_MODEL


def get_inital_shaping():
    start_time = time.perf_counter()

    # 1. Initialize Workspace & Ledger for Iteration 0
    ws = ExperimentWorkspace(iteration=0)
    brain = CognitiveNode(iteration=0, workspace=ws, model=MODEL_NAME)
    ledger = ExperimentLedger(ws.model_root_path)
    
    save_path = ws.get_path("code", 0, "reward.py") 
    
    print("🔵 AGENT (Iter 0): Generating Initial Reward Function, Based On Physics Heuristics")
    sys_prompt = prompts.load_template('system_prompts','initial','initial_system_prompt')
    user_prompt = prompts.load_template('user_prompts','initial','initial_user_prompt')

    response = brain.chat(
        phase_name='initial',
        system_prompt=sys_prompt,
        user_prompt=user_prompt,
        options=Config.think_options
    )
    
    clean_code = "import numpy as np\nimport math\n" 
    clean_code += extract_python_code(response)
        
    validator = CodeValidator(clean_code)
    is_valid, feedback = validator.validate()

    # --- RETRY LOOP ---
    attempt_num = 0
    while not is_valid and attempt_num < 3:
        attempt_num += 1
        print(f"⚠️ Validation failed (Attempt {attempt_num}). Feedback: {feedback}")
        
        fail_filename = f"fail_{attempt_num:02d}.py"
        fail_path = ws.get_path("failed_code", 0, fail_filename)
        
        with open(fail_path, "w") as f:
            f.write(f"# Error: {feedback}\n")
            f.write(clean_code)
            
        user_prompt += (
            f"\n\nYour previous attempt failed validation with the following error:\n"
            f"ERROR: {feedback}\n"
            f"Please analyze the error, fix the code, and output ONLY the corrected Python code inside a markdown block."
            f"Below is your previous generated code\n"
            f"{clean_code}"
        )
        code_fix_response = brain.chat(
            phase_name='code_fix',
            system_prompt=sys_prompt,
            user_prompt=user_prompt,
            options=Config.think_options
        )
        
        clean_code = "import numpy as np\nimport math\n" 
        clean_code += extract_python_code(code_fix_response)
        
        validator = CodeValidator(clean_code)
        is_valid, feedback = validator.validate()

    # --- SAVE ARTIFACTS ---
    if is_valid:
        timestamp_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        final_content = f"# Generated by {MODEL_NAME} (Iter 0) on {timestamp_str}\n" + clean_code
        
        try:
            with open(save_path, "w") as f:
                f.write(final_content)
            print(f"✅ Code validated and saved to {save_path}")
            
            # CRITICAL: Log Iteration 0 Intent so Iteration 1 can validate it
            initial_hypothesis = "Iteration 0 Baseline: Implemented basic physics heuristics (minimize velocity, stay upright, approach target) to establish stable initial PPO training."
            ledger.log_hypothesis(iteration=0, validator_payload=initial_hypothesis)
            print("📓 Baseline hypothesis logged to ledger.")
            
        except Exception as e:
            print(f"❌ Error saving code: {e}")
    else:
        print("❌ CRITICAL: Failed to generate valid code after 3 attempts.")

    brain.save_report()
    elapsed_time = time.perf_counter() - start_time
    print(f"Execution took: {timedelta(seconds=elapsed_time)}")

if __name__ == "__main__":
    get_inital_shaping()