# Generated by gemma4:26b-mlx (Iter 8) on 2026-06-14 01:32:00
import math
import numpy as np
from typing import Dict, Tuple

def calculate_reward(obs: np.ndarray, info: Dict) -> Tuple[float, Dict[str, float]]:
    """
    Args:
        obs: Current observation [x, y, vx, vy, angle, v_ang, leg1, leg2]
        info: {'prev_obs': prev_obs, 'action': action_idx, 'terminal_observation': term_obs, 'current_step': curr_step}
    
    Returns:
        total_reward (float): The sum of all shaping components for this step.
        components (dict): Granular breakdown of the reward components.
    """
    
    x, y, vx, vy, angle, v_ang, leg1, leg2 = obs
    prev_obs = info.get('prev_obs', obs)
    prev_vx, prev_legs, prev_action = prev_obs[2], prev_obs[6] + prev_obs[7], info.get('prev_action', 0)
    action = info.get('action', 0)
    
    # === 1. LEG CONTACT + HORIZONTAL SLIDE (core reward) ===
    legs_contact = leg1 + leg2
    horiz_slide_speed = abs(vx)
    
    # === 3. HORIZONTAL DIRECTION CHANGES (slalom sliding) ===
    vx_sign_flip = (np.sign(vx) != np.sign(prev_vx)) and abs(vx) > 0.8
    
    # === 5. GROUND LEVEL PREFERENCE (slide near y=0) ===
    r_ground_level = 4.5 * np.exp(-y**2 / 0.08) - 1.5
    
    # === 7. SURVIVAL + LEG MAINTENANCE ===
    r_survival = 0.1
    r_leg_maintenance = 1.0 * legs_contact  # Keep at least one leg down
    
    # === 8. ORIENTATION PENALTY ===
    r_orientation = -(10.0 * angle**2 + 2.0 * v_ang**2)
    
    # === 9. VELOCITY STABILITY PENALTY ===
    r_velocity_stability = -(3.0 * vy**2 + 10.0 * vx**2)
    
    # === 6. PENALIZE VERTICAL MOTION (stay low) ===
    r_vertical_penalty = -2.0 * vy**2
    
    # === 11. LATERAL VISCOUS DRAG (new component) ===
    r_lateral_viscosity = -6.0 * (1.0 - np.clip(y, 0, 1)) * vx**2
    
    # === NEW: SETTLE COMPONENTS ===
    r_settle_v = -25.0 * (vx**2 + vy**2)  # Kinetic Energy Damping
    r_settle_a = -25.0 * angle**2         # Rotational Alignment
    gate = np.clip((0.5 - y) / 0.5, 0, 1)  # Altitude Gating
    r_landing_precision = (r_settle_v + r_settle_a) * gate
    
    components = {
        "ground_level": float(r_ground_level),
        "vertical_penalty": float(r_vertical_penalty),
        "leg_maintenance": float(r_leg_maintenance),
        "orientation_penalty": float(r_orientation),
        "velocity_stability": float(r_velocity_stability),
        "lateral_viscosity": float(r_lateral_viscosity),
        "landing_precision": float(r_landing_precision),
    }
    
    total_reward = float(sum(components.values()))
    return total_reward, components