# Generated by gemma3:27b (Iter 15) on 2026-04-15 05:57:26
import math
import numpy as np
from typing import Dict, Tuple

def calculate_reward(obs: np.ndarray, info: Dict) -> Tuple[float, Dict[str, float]]:
    """
    Args:
        obs: Current observation [x, y, vx, vy, angle, v_ang, leg1, leg2]
        info: {'prev_obs': prev_obs, 'action': action_idx, 'terminal_observation': term_obs, 'current_step': curr_step}
    
    Returns:
        total_reward (float): The sum of all shaping components for this step.
        components (dict): Granular breakdown of the reward components.
    """
    
    x, y, vx, vy, angle, v_ang, leg1, leg2 = obs
    prev_obs = info.get('prev_obs', obs)
    prev_action = info.get('action', 0)
    prev_y = prev_obs[1]
    prev_angle = prev_obs[4]
    prev_v_ang = prev_obs[5]
    
    # === 1. DESCENT BONUS (UPDATED) ===
    # R_descent = α * max(0, vy) * (y_prev - y)
    # where α = 0.5
    alpha = 0.5
    r_descent = alpha * max(0, vy) * (prev_y - y)
    
    # === 2. LEG CONTACT PENALTY (MAINTAINED) ===
    # R_legs = 5.0 * (leg1 + leg2)
    r_legs = 5.0 * (leg1 + leg2)
    
    # === 3. VERTICAL VELOCITY PENALTY (MAINTAINED) ===
    # R_vertical = -β * abs(vy)
    # where β = 0.5
    beta = 0.5
    r_vertical = -beta * abs(vy)
    
    # === 4. MOMENTUM PENALTY (MAINTAINED) ===
    # R_momentum = α * (vy * -1) * max(0, 1 - abs(x_pos))
    # where α = 0.8
    alpha_momentum = 0.8
    r_momentum = alpha_momentum * (vy * -1) * max(0, 1 - abs(x))
    
    # === 5. ANGULAR MOMENTUM PENALTY (MAINTAINED) ===
    # R_angular = - α * (v_ang^2) * (1 + γ * |vy|)
    # where α = 0.3, γ = 0.2
    alpha_angular = 0.3
    gamma_angular = 0.2
    r_angular = -alpha_angular * (v_ang ** 2) * (1 + gamma_angular * abs(vy))
    
    # === 6. DYNAMIC ANGULAR DAMPING PENALTY (UPDATED) ===
    # R_angular_damping = -β * |vy| * (θ^2 + ṡ^2)
    # where β = 0.1
    beta_damping = 0.1
    r_angular_damping = -beta_damping * abs(vy) * (angle ** 2 + v_ang ** 2)
    
    # === 7. ACTION SMOOTHNESS REWARD (MAINTAINED) ===
    # R_action_regularization = 0.2 * (1 - abs(action - prev_action))
    r_action_regularization = 0.2 * (1 - abs(prev_action - info.get('action', 0)))
    
    # === 8. ACTION CONTINUITY REWARD (MAINTAINED) ===
    # R_action_continuity = γ * exp(-abs(action - prev_action))
    # where γ = 0.02
    gamma_continuity = 0.02
    r_action_continuity = gamma_continuity * math.exp(-abs(prev_action - info.get('action', 0)))
    
    # === 9. LATERAL STABILITY REWARD (MAINTAINED) ===
    # R_lateral_stability = α * exp(-abs(x) / σ)
    # where α = 0.1, σ = 0.5
    alpha_lateral = 0.1
    sigma_lateral = 0.5
    r_lateral_stability = alpha_lateral * math.exp(-abs(x) / sigma_lateral)
    
    # === 10. LATERAL VELOCITY PENALTY (MAINTAINED) ===
    # R_lateral_velocity_penalty = -alpha_lateral * abs(vx) * (1 + (y/5))
    # where alpha_lateral = 0.1
    r_lateral_velocity_penalty = -alpha_lateral * abs(vx) * (1 + (y/5))
    
    # === 11. COMBINE ALL COMPONENTS ===
    components = {
        "descent_bonus": float(r_descent),
        "leg_contact_penalty": float(r_legs),
        "vertical_velocity_penalty": float(r_vertical),
        "momentum_penalty": float(r_momentum),
        "angular_penalty": float(r_angular),
        "angular_damping_penalty": float(r_angular_damping),
        "action_regularization_reward": float(r_action_regularization),
        "action_continuity_reward": float(r_action_continuity),
        "lateral_stability_reward": float(r_lateral_stability),
        "lateral_velocity_penalty": float(r_lateral_velocity_penalty),
    }
    
    total_reward = float(sum(components.values()))
    return total_reward, components