# Generated by gemma4:26b-mlx (Iter 1) on 2026-06-14 00:34:57
import math
import numpy as np
from typing import Dict, Tuple

def calculate_reward(obs: np.ndarray, info: Dict) -> Tuple[float, Dict[str, float]]:
    """
    Args:
        obs: Current observation [x, y, vx, vy, angle, v_ang, leg1, leg2]
        info: {'prev_obs': prev_obs, 'action': action_idx, 'terminal_observation': term_obs, 'current_step': curr_step}
    
    Returns:
        total_reward (float): The sum of all shaping components for this step.
        components (dict): Granular breakdown of the reward components.
    """
    
    x, y, vx, vy, angle, v_ang, leg1, leg2 = obs
    prev_obs = info.get('prev_obs', obs)
    prev_vx, prev_legs = prev_obs[2], prev_obs[6] + prev_obs[7]
    action = info.get('action', 0)
    
    # === 1. LEG CONTACT + HORIZONTAL SLIDE (core reward) ===
    legs_contact = leg1 + leg2
    horiz_slide_speed = abs(vx)
    
    # Massive bonus for legs down AND sliding fast sideways
    sliding_legs = legs_contact * horiz_slide_speed
    r_sliding_legs = 12.0 * np.clip(sliding_legs / 2.0, 0, 1.5)  # up to +18!
    
    # === 3. HORIZONTAL DIRECTION CHANGES (slalom sliding) ===
    vx_sign_flip = (np.sign(vx) != np.sign(prev_vx)) and abs(vx) > 0.8
    r_slalom = 6.0 if vx_sign_flip else 0.0
    
    # === 5. GROUND LEVEL PREFERENCE (slide near y=0) ===
    near_ground = abs(y) < 0.4
    r_ground_level = 3.0 if near_ground else -1.5
    
    # === 6. PENALIZE VERTICAL MOTION (stay low) ===
    r_vertical_penalty = -2.0 * abs(vy)  # Hate up/down
    
    # === 7. SURVIVAL + LEG MAINTENANCE ===
    r_survival = 0.1
    r_leg_maintenance = 1.0 * legs_contact  # Keep at least one leg down
    
    # === 8. ORIENTATION PENALTY ===
    r_orientation = -(10.0 * angle**2 + 2.0 * abs(v_ang))
    
    components = {
        "sliding_legs": float(r_sliding_legs),
        "slalom_bonus": float(r_slalom),
        "ground_level": float(r_ground_level),
        "vertical_penalty": float(r_vertical_penalty),
        "leg_maintenance": float(r_leg_maintenance),
        "orientation_penalty": float(r_orientation),
    }
    
    total_reward = float(sum(components.values()))
    return total_reward, components