# Generated by gemma3:27b (Iter 8) on 2026-04-15 04:34:28
# Generated by gemma3:27b (Iter 7) on 2026-04-15 04:22:39
import math
import numpy as np
from typing import Dict, Tuple

def calculate_reward(obs: np.ndarray, info: Dict) -> Tuple[float, Dict[str, float]]:
    """
    Args:
        obs: Current observation [x, y, vx, vy, angle, v_ang, leg1, leg2]
        info: {'prev_obs': prev_obs, 'action': action_idx, 'terminal_observation': term_obs, 'current_step': curr_step}
    
    Returns:
        total_reward (float): The sum of all shaping components for this step.
        components (dict): Granular breakdown of the reward components.
    """
    
    x, y, vx, vy, angle, v_ang, leg1, leg2 = obs
    prev_obs = info.get('prev_obs', obs)
    prev_action = info.get('action', 0)
    prev_y = prev_obs[1]
    
    # === 1. DESCENT BONUS (UPDATED) ===
    # R_descent = α * y * max(0, vy)
    # where α = 0.05
    alpha = 0.05
    r_descent = alpha * y * max(0, vy)
    
    # === 2. LEG CONTACT PENALTY (MAINTAINED) ===
    # R_legs = 5.0 * (leg1 + leg2)
    r_legs = 5.0 * (leg1 + leg2)
    
    # === 3. VERTICAL VELOCITY PENALTY (UPDATED) ===
    # R_vertical = -β * abs(vy)
    # where β = 0.5
    beta = 0.5
    r_vertical = -beta * abs(vy)
    
    # === 4. MOMENTUM PENALTY (MAINTAINED) ===
    # R_momentum = α * (vy * -1) * max(0, 1 - abs(x_pos))
    # where α = 0.8
    alpha_momentum = 0.8
    r_momentum = alpha_momentum * (vy * -1) * max(0, 1 - abs(x))
    
    # === 5. ANGULAR MOMENTUM PENALTY (MAINTAINED) ===
    # R_angular_momentum = -α * (v_ang)^2 - β * v_ang
    # where α = 0.1, β = 0.01
    alpha_angular = 0.1
    beta_angular = 0.01
    r_angular_momentum = -alpha_angular * (v_ang ** 2) - beta_angular * v_ang
    
    # === 6. DYNAMIC ANGULAR DAMPING PENALTY ===
    # R_angular_damping = -α * (v_ang)^2 * (1 - y / 10)
    # where α = 0.15
    alpha_damping = 0.15
    r_angular_damping = -alpha_damping * (v_ang ** 2) * (1 - y / 10)
    
    # === 7. ACTION SMOOTHNESS REWARD ===
    # R_action_smoothness = γ * (1 - abs(action - prev_action))
    # where γ = 0.01
    gamma_smoothness = 0.01
    r_action_smoothness = gamma_smoothness * (1 - abs(prev_action - info.get('action', 0)))
    
    # === 8. LATERAL STABILITY REWARD ===
    # R_lateral_stability = α * exp(-abs(x) / σ)
    # where α = 0.1, σ = 0.5
    alpha_lateral = 0.1
    sigma_lateral = 0.5
    r_lateral_stability = alpha_lateral * math.exp(-abs(x) / sigma_lateral)
    
    # === 9. HOVER PENALTY ===
    # R_hover_penalty = -β * max(0, (1 - vy))
    # where β = 0.02
    beta_hover = 0.02
    r_hover_penalty = -beta_hover * max(0, (1 - vy))
    
    # === 10. COMBINE ALL COMPONENTS ===
    components = {
        "descent_bonus": float(r_descent),
        "leg_contact_penalty": float(r_legs),
        "vertical_velocity_penalty": float(r_vertical),
        "momentum_penalty": float(r_momentum),
        "angular_momentum_penalty": float(r_angular_momentum),
        "angular_damping_penalty": float(r_angular_damping),
        "action_smoothness_reward": float(r_action_smoothness),
        "lateral_stability_reward": float(r_lateral_stability),
        "hover_penalty": float(r_hover_penalty),
    }
    
    total_reward = float(sum(components.values()))
    return total_reward, components