# Generated by gemma3:27b (Iter 2) on 2026-04-15 03:27:55
import math
import numpy as np
from typing import Dict, Tuple

def calculate_reward(obs: np.ndarray, info: Dict) -> Tuple[float, Dict[str, float]]:
    """
    Args:
        obs: Current observation [x, y, vx, vy, angle, v_ang, leg1, leg2]
        info: {'prev_obs': prev_obs, 'action': action_idx, 'terminal_observation': term_obs, 'current_step': curr_step}
    
    Returns:
        total_reward (float): The sum of all shaping components for this step.
        components (dict): Granular breakdown of the reward components.
    """
    
    x, y, vx, vy, angle, v_ang, leg1, leg2 = obs
    prev_obs = info.get('prev_obs', obs)
    prev_angle, prev_v_ang = prev_obs[4], prev_obs[5]
    action = info.get('action', 0)
    
    # === 1. ANGULAR VELOCITY OBSESSION (primary reward) ===
    # Massive bonus for HIGH |v_ang| (spinning fast)
    spin_speed = abs(v_ang)
    r_spin_speed = 10.0 * np.clip(spin_speed / 3.0, 0, 2.0)  # up to +20!
    
    # Bonus for angle magnitude (being rotated)
    r_spin_angle = 4.0 * np.abs(angle)  # up to ~12 for ±π
    
    # Angular acceleration bonus (changing spin rate)
    d_angle = abs(angle - prev_angle)
    r_spin_accel = 2.0 * np.clip(d_angle / np.pi, 0, 1.0)  # up to +2
    
    # === 2. SPIN DIRECTION CHANGE (alternating spin directions) ===
    v_ang_sign_flip = (np.sign(v_ang) != np.sign(prev_v_ang)) and abs(v_ang) > 1.0
    r_spin_flip = 8.0 if v_ang_sign_flip else 0.0
    
    # === 3. ACTION PREFERENCE (thrusters that induce torque) ===
    # All actions except do-nothing get spin bonus
    if action == 0:  # do nothing
        r_action = -1.0
    else:  # any thrust = torque potential
        r_action = 0.5
    
    # === 4. IGNORE LANDING (no leg/position rewards) ===
    # Mild penalty for legs touching (interrupts spin)
    r_legs_penalty = -2.0 * (leg1 + leg2)
    
    # === 5. SURVIVAL (allow long spin episodes) ===
    r_survival = 0.08
    
    # === 6. VERTICAL TOLERANCE (don't care much about y/vy) ===
    # Mild preference for level flight to prolong spinning
    r_vertical = -0.3 * abs(vy)  # Don't crash vertically too fast
    
    # === 7. NEW LEG CONTACT REWARD COMPONENT ===
    # R_leg_contact = λ * (leg1 + leg2) * exp(-μ * y) * max(0, 1 - |v_y| / δ)
    # λ = 3.0, μ = 0.2, δ = 2.0
    lambda_param = 3.0
    mu_param = 0.2
    delta_param = 2.0
    r_leg_contact = lambda_param * (leg1 + leg2) * np.exp(-mu_param * y) * max(0, 1 - abs(vy) / delta_param)
    
    components = {
        "spin_speed": float(r_spin_speed),
        "spin_angle": float(r_spin_angle),
        "spin_accel": float(r_spin_accel),
        "spin_direction_flip": float(r_spin_flip),
        "action_spin_bonus": float(r_action),
        "legs_interrupt_penalty": float(r_legs_penalty),
        "survival": float(r_survival),
        "vertical_tolerance": float(r_vertical),
        "leg_contact_reward": float(r_leg_contact),
    }
    
    total_reward = float(sum(components.values()))
    return total_reward, components