# Generated by gemma4:26b (Iter 2) on 2026-05-09 18:01:13
import math
import numpy as np
from typing import Dict, Tuple

def calculate_reward(obs: np.ndarray, info: Dict) -> Tuple[float, Dict[str, float]]:
    """
    Args:
        obs: Current observation [x, y, vx, vy, angle, v_ang, leg1, leg2]
        info: {'prev_obs': prev_obs, 'action': action_idx, 'terminal_observation': term_obs, 'current_step': curr_step}
    
    Returns:
        total_reward (float): The sum of all shaping components for this step.
        components (dict): Granular breakdown of the reward components.
    """
    
    x, y, vx, vy, angle, v_ang, leg1, leg2 = obs
    prev_obs = info.get('prev_obs', obs)
    prev_angle, prev_v_ang = prev_obs[4], prev_obs[5]
    action = info.get('action', 0)
    
    # === 1. ATTITUDE PENALTY (new addition) ===
    w_att = 1.5
    r_attitude = -w_att * (angle**2 + v_ang**2)
    
    # === 2. IGNORE LANDING (no leg/position rewards) ===
    # Mild penalty for legs touching (interrupts spin)
    r_legs_penalty = -2.0 * (leg1 + leg2)
    
    # === 3. SINK PENALTY (new addition) ===
    w_x = 0.5
    w_y = 0.5
    w_v = 0.2
    r_sink = -(w_x * np.abs(x) + w_y * np.abs(y) + w_v * (vy**2))
    
    components = {
        "attitude_penalty": float(r_attitude),
        "legs_interrupt_penalty": float(r_legs_penalty),
        "sink_penalty": float(r_sink),
    }
    
    total_reward = float(sum(components.values()))
    return total_reward, components