# Generated by gemma4:26b (Iter 7) on 2026-05-09 19:12:56
import math
import numpy as np
from typing import Dict, Tuple

def calculate_reward(obs: np.ndarray, info: Dict) -> Tuple[float, Dict[str, float]]:
    """
    Args:
        obs: Current observation [x, y, vx, vy, angle, v_ang, leg1, leg2]
        info: {'prev_obs': prev_obs, 'action': action_idx, 'terminal_observation': term_obs, 'current_step': curr_step}
    
    Returns:
        total_reward (float): The sum of all shaping components for this step.
        components (dict): Granular breakdown of the reward components.
    """
    
    x, y, vx, vy, angle, v_ang, leg1, leg2 = obs
    prev_obs = info.get('prev_obs', obs)
    prev_angle, prev_v_ang = prev_obs[4], prev_obs[5]
    action = info.get('action', 0)
    
    # === 1. ATTITUDE PENALTY (new addition) ===
    w_att = 1.5
    r_attitude = -w_att * (angle**2 + v_ang**2)
    
    # === 2. SINK PENALTY (new addition) ===
    w_x = 0.5
    w_y = 0.5
    w_v = 0.2
    r_sink = -(w_x * np.abs(x) + w_y * np.abs(y) + w_v * (vy**2))
    
    # === 3. SMOOTHNESS PENALTY (new addition) ===
    w_smooth = 0.1
    prev_action = info.get('prev_action', 0)
    r_smooth = -w_smooth * np.abs(action - prev_action)
    
    # === 4. FUNNEL PENALTY (new addition) ===
    w_L = 2.0
    w_I = 5.0
    k = 10.0
    sigmoid_y = 1.0 / (1.0 + np.exp(-k * (0.5 - y)))
    r_funnel = -w_L * (x**2 + vx**2) * (1.0 - sigmoid_y) - w_I * (vy**2) * sigmoid_y
    
    components = {
        "attitude_penalty": float(r_attitude),
        "sink_penalty": float(r_sink),
        "smoothness_penalty": float(r_smooth),
        "funnel_penalty": float(r_funnel),
    }
    
    total_reward = float(sum(components.values()))
    return total_reward, components