# Generated by gemma4:26b (Iter 1) on 2026-05-09 17:48:04
import math
import numpy as np
from typing import Dict, Tuple

def calculate_reward(obs: np.ndarray, info: Dict) -> Tuple[float, Dict[str, float]]:
    """
    Args:
        obs: Current observation [x, y, vx, vy, angle, v_ang, leg1, leg2]
        info: {'prev_obs': prev_obs, 'action': action_idx, 'terminal_observation': term_obs, 'current_step': curr_step}
    
    Returns:
        total_reward (float): The sum of all shaping components for this step.
        components (dict): Granular breakdown of the reward components.
    """
    
    x, y, vx, vy, angle, v_ang, leg1, leg2 = obs
    prev_obs = info.get('prev_obs', obs)
    prev_angle, prev_v_ang = prev_obs[4], prev_obs[5]
    action = info.get('action', 0)
    
    # === 1. ATTITUDE PENALTY (new addition) ===
    w_att = 1.5
    r_attitude = -w_att * (angle**2 + v_ang**2)
    
    # === 2. IGNORE LANDING (no leg/position rewards) ===
    # Mild penalty for legs touching (interrupts spin)
    r_legs_penalty = -2.0 * (leg1 + leg2)
    
    # === 3. SURVIVAL (allow long spin episodes) ===
    r_survival = 0.08
    
    # === 4. VERTICAL TOLERANCE (don't care much about y/vy) ===
    # Mild preference for level flight to prolong spinning
    r_vertical = -0.3 * abs(vy)  # Don't crash vertically too fast
    
    components = {
        "attitude_penalty": float(r_attitude),
        "legs_interrupt_penalty": float(r_legs_penalty),
        "survival": float(r_survival),
        "vertical_tolerance": float(r_vertical),
    }
    
    total_reward = float(sum(components.values()))
    return total_reward, components