# Generated by gemma4:26b (Iter 3) on 2026-05-09 18:14:36
import math
import numpy as np
from typing import Dict, Tuple

def calculate_reward(obs: np.ndarray, info: Dict) -> Tuple[float, Dict[str, float]]:
    """
    Args:
        obs: Current observation [x, y, vx, vy, angle, v_ang, leg1, leg2]
        info: {'prev_obs': prev_obs, 'action': action_idx, 'terminal_observation': term_obs, 'current_step': curr_step}
    
    Returns:
        total_reward (float): The sum of all shaping components for this step.
        components (dict): Granular breakdown of the reward components.
    """
    
    x, y, vx, vy, angle, v_ang, leg1, leg2 = obs
    prev_obs = info.get('prev_obs', obs)
    prev_angle, prev_v_ang = prev_obs[4], prev_obs[5]
    action = info.get('action', 0)
    
    # === 1. ATTITUDE PENALTY (new addition) ===
    w_att = 1.5
    r_attitude = -w_att * (angle**2 + v_ang**2)
    
    # === 2. SINK PENALTY (new addition) ===
    w_x = 0.5
    w_y = 0.5
    w_v = 0.2
    r_sink = -(w_x * np.abs(x) + w_y * np.abs(y) + w_v * (vy**2))
    
    # === 3. SMOOTHNESS PENALTY (new addition) ===
    w_smooth = 0.1
    prev_action = info.get('prev_action', 0)
    r_smooth = -w_smooth * np.abs(action - prev_action)
    
    components = {
        "attitude_penalty": float(r_attitude),
        "sink_penalty": float(r_sink),
        "smoothness_penalty": float(r_smooth),
    }
    
    total_reward = float(sum(components.values()))
    return total_reward, components