# Generated by gemma4:26b (Iter 10) on 2026-05-09 19:57:11
import math
import numpy as np
from typing import Dict, Tuple

def calculate_reward(obs: np.ndarray, info: Dict) -> Tuple[float, Dict[str, float]]:
    """
    Args:
        obs: Current observation [x, y, vx, vy, angle, v_ang, leg1, leg2]
        info: {'prev_obs': prev_obs, 'action': action_idx, 'terminal_observation': term_obs, 'current_step': curr_step}
    
    Returns:
        total_reward (float): The sum of all shaping components for this step.
        components (dict): Granular breakdown of the reward components.
    """
    
    x, y, vx, vy, angle, v_ang, leg1, leg2 = obs
    prev_obs = info.get('prev_obs', obs)
    prev_angle, prev_v_ang = prev_obs[4], prev_obs[5]
    action = info.get('action', 0)
    
    # === 1. ATTITUDE PENALTY (new addition) ===
    w_att = 1.5
    r_attitude = -w_att * (angle**2 + v_ang**2)
    
    # === 2. SINK PENALTY (new addition) ===
    w_x = 2.5  # Rescaled upward by ~5.0
    w_y = 0.5
    w_v = 1.0  # Rescaled upward by ~5.0
    # Gating factor: 1.0 at high altitude, 0.0 at ground level
    precision_gate = 1.0 - (1.0 / (1.0 + np.exp(-10.0 * (y - 0.5)))) 
    # Only penalize lateral error and impact velocity as y approaches 0
    r_sink = -(w_x * np.abs(x) * precision_gate + w_v * (vy**2) * (1.0 - precision_gate))
    
    # === 3. STABILITY BONUS (new addition) ===
    w_stab = 0.2
    prev_action = info.get('prev_action', 0)
    r_stability = w_stab * np.exp(-np.abs(action - prev_action))
    
    # === 4. FUNNEL PENALTY (new addition) ===
    w_L = 2.0
    w_I = 5.0
    k = 10.0
    sigmoid_y = 1.0 / (1.0 + np.exp(-k * (0.5 - y)))
    r_funnel = -w_L * (x**2 + vx**2) * (1.0 - sigmoid_y) - w_I * (vy**2) * sigmoid_y
    
    # === 5. PRECISION PENALTY (new addition) ===
    w_L = 5.0
    sigmoid_y = 1.0 / (1.0 + np.exp(-10.0 * (0.5 - y)))
    # Activation only when y < 0.5
    r_precision = w_L * sigmoid_y * np.exp(-(x**2 + vx**2 + vy**2))
    
    components = {
        "attitude_penalty": float(r_attitude),
        "sink_penalty": float(r_sink),
        "stability_bonus": float(r_stability),
        "funnel_penalty": float(r_funnel),
        "precision_penalty": float(r_precision),
    }
    
    total_reward = float(sum(components.values()))
    return total_reward, components