# Generated by gemma3:27b (Iter 3) on 2026-04-15 03:39:15
import math
import numpy as np
from typing import Dict, Tuple

def calculate_reward(obs: np.ndarray, info: Dict) -> Tuple[float, Dict[str, float]]:
    """
    Args:
        obs: Current observation [x, y, vx, vy, angle, v_ang, leg1, leg2]
        info: {'prev_obs': prev_obs, 'action': action_idx, 'terminal_observation': term_obs, 'current_step': curr_step}
    
    Returns:
        total_reward (float): The sum of all shaping components for this step.
        components (dict): Granular breakdown of the reward components.
    """
    
    x, y, vx, vy, angle, v_ang, leg1, leg2 = obs
    prev_obs = info.get('prev_obs', obs)
    prev_y = prev_obs[1]
    
    # === 1. DESCENT BONUS (NEW) ===
    # R_descent = α * max(0, -y_change)
    # where α = 5.0
    alpha = 5.0
    y_change = y - prev_y
    r_descent = alpha * max(0, -y_change)
    
    # Clip the descent bonus to avoid overly aggressive rewards
    r_descent = np.clip(r_descent, 0, 10.0)
    
    # === 2. LEG CONTACT PENALTY (NEW) ===
    # R_legs = 5.0 * (leg1 + leg2)
    r_legs = 5.0 * (leg1 + leg2)
    
    # === 3. VERTICAL VELOCITY PENALTY (MAINTAINED) ===
    # R_vertical = -0.3 * abs(vy)
    r_vertical = -0.3 * abs(vy)
    
    # === 4. COMBINE ALL COMPONENTS ===
    components = {
        "descent_bonus": float(r_descent),
        "leg_contact_penalty": float(r_legs),
        "vertical_velocity_penalty": float(r_vertical),
    }
    
    total_reward = float(sum(components.values()))
    return total_reward, components