import json
from datetime import datetime
from typing import Dict, Optional, Any
from pathlib import Path

class ExperimentLedger:
    def __init__(self, workspace_root: Path):
        """
        Initialize the Ledger within the workspace structure.
        """
        self.filepath = workspace_root / "cognition" / "experiment_ledger.json"
        self.history = self._load_history() 

    def _load_history(self) -> Dict[str, Any]:
        """Loads current experiement ledger JSON, returns Python dictionary"""
        if self.filepath.exists():
            try:
                with open(self.filepath, 'r') as f:
                    return json.load(f)
            except json.JSONDecodeError:
                print("⚠️  Ledger corrupted. Starting fresh.")
        
        return {"project": "RL_ARD_Loop", "experiments": []}

    def _save(self):
        self.filepath.parent.mkdir(parents=True, exist_ok=True)
        with open(self.filepath, 'w') as f:
            json.dump(self.history, f, indent=4)

    def get_last_experiment_id(self) -> Optional[int]:
        """Returns the ID of the most recent experiment."""
        if not self.history["experiments"]:
            return None
        return self.history["experiments"][-1]["id"]

    def log_hypothesis(self, iteration: int, validator_payload: str):
        """
        Phase 1: Logs the scientific hypothesis extracted by the Dispatcher 
        BEFORE the agent starts training.
        """
        new_entry = {
            "id": iteration,
            "timestamp": datetime.now().isoformat(),
            "hypothesis_payload": validator_payload,
            "validation_post_mortem": None  # To be filled after training
        }
        self.history["experiments"].append(new_entry)
        self._save()

    def log_validation(self, iteration: int, validator_bullets: str):
        """
        Phase 2: Logs the 3-bullet post-mortem generated by the Validator 
        AFTER the agent has trained and been evaluated.
        """
        for exp in self.history["experiments"]:
            if exp["id"] == iteration:
                exp["validation_post_mortem"] = validator_bullets
                self._save()
                return
        print(f"⚠️  Could not find Iteration {iteration} in ledger to append validation.")
    
    def get_hypothesis(self, iteration: int) -> str:
            """
            Retrieves the scientific hypothesis generated in a previous run 
            so the Validator can evaluate it against the new telemetry.
            """
            for exp in self.history["experiments"]:
                if exp["id"] == iteration:
                    return exp.get("hypothesis_payload", "")
            return "No hypothesis found for this iteration."
    
    def get_context_for_llm(self, limit: int = 5) -> str:
        """
        Formats the most recent completed experiments into a pristine 
        Markdown string for the Strategist and Research Lead.
        """
        # Only grab experiments that have a completed validation post-mortem
        completed = [e for e in self.history["experiments"] if e.get("validation_post_mortem")]
        recent = completed[-limit:]
        
        if not recent:
            return "First Iteration: No Past Intervention Records Yet"

        history_blocks = []
        for exp in recent:
            block = f"### Iteration {exp['id']} Historical Record\n"
            block += "**The Proposed Intervention:**\n"
            block += f"{exp['hypothesis_payload']}\n\n"
            block += "**The Physical Outcome & Lesson:**\n"
            block += f"{exp['validation_post_mortem']}\n"
            block += "-" * 40
            history_blocks.append(block)
            
        return "\n\n".join(history_blocks)